name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ دریافت سورس کد
    - uses: actions/checkout@v4

    # 2️⃣ نصب Java
    - uses: actions/setup-java@v5.1.0
      with:
        distribution: temurin
        java-version: 17

    # 3️⃣ کش Gradle
    - name: Cache Gradle
      uses: actions/cache@v4.3.0
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    # 4️⃣ دادن اجازه اجرایی به gradlew و ساخت APK   
    # 5️⃣ آپلود APK ساخته شده
    - name: Upload APK
      uses: actions/upload-artifact@v5.0.0
      with:
        name: EpsilonVPN-debug.apk
        path: EpsilonVpn
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Gradle Permission
      run: chmod +x gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Build APK
      working-directory: EpsilonVpn       # <-- ریشه پروژه
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
